cd desktop/ml-course/sample-project
conda env list 
conda activate /Users/daniel/

In [1]:
import numpy as np

### 1. DataTypes & Attributes 

In [17]:
# Numpy's main datatype is ndarray 
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
type(al)

numpy.ndarray

In [8]:
a2 = np.array([[1,2,3],
              [4,5,6.5]])

a3= np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
              [[10,11,12],
               [13,14,15],
               [16,17,18]]])

In [9]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [10]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [13]:
a1.shape

(3,)

In [14]:
a2.shape

(2, 3)

In [15]:
a3.shape

(2, 3, 3)

In [16]:
# dimensions 
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [18]:
# dtype 
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [21]:
# size, how many elements in total 
a1.size, a2.size, a3.size

(3, 6, 18)

In [22]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [23]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.5

### 2. Creating arrays


In [24]:
sample_array = np.array([1,2,4])
sample_array

array([1, 2, 4])

In [26]:
sample_array.dtype

dtype('int32')

In [33]:
ones = np.ones((2,3,2), dtype= int)
# return a new arrat of given shape and type
ones
type(ones)

numpy.ndarray

In [35]:
zeros = np.zeros((2,3))
zeros 

array([[0., 0., 0.],
       [0., 0., 0.]])

In [37]:
# numpy.arange()
# Return evenly spaced values within a given interval 
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [39]:
# numpy.random.randint()
# Return random integers from the 'distribution of the specified dtype '
random_array = np.random.randint(1,10, size=(3,5))
random_array

array([[1, 6, 3, 1, 4],
       [1, 4, 7, 4, 6],
       [3, 5, 6, 4, 8]])

In [40]:
random_array.shape

(3, 5)

In [45]:
# numpy.random.random 
# Return ranodm floats in the interval [0.0,1.0)

random_array_2 = np.random.random((5,3))
random_array_2

array([[0.45042658, 0.13093057, 0.24943452],
       [0.29045416, 0.26343837, 0.4848837 ],
       [0.32255372, 0.33387982, 0.5348181 ],
       [0.71825725, 0.34512954, 0.83425053],
       [0.87396704, 0.50110736, 0.40720872]])

In [46]:
random_array_2.shape

(5, 3)

In [47]:
random_array_3 = np.random.rand(5,3)
random_array_3

# Random values in a given shape 

array([[0.44902714, 0.80341734, 0.62690971],
       [0.89764192, 0.0371594 , 0.81314663],
       [0.59737102, 0.7166539 , 0.98397299],
       [0.9062409 , 0.24145341, 0.16556472],
       [0.04864325, 0.96678865, 0.8338307 ]])

In [63]:
# Pseudo-random number 
# np.random.seed()

np.random.seed(seed= 0)

random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [49]:
random_array_4.shape

(5, 3)

In [61]:
np.random.seed(7)
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

### 3. Viewing arrays and matrices

In [64]:
# how to find unique elements in an array 

np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
a1
a1[0]

1

In [70]:
a2
a2[0]

array([1., 2., 3.])

In [67]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [74]:
a3.shape

(2, 3, 3)

In [75]:
a3[0].shape

(3, 3)

In [76]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[6, 7, 7, 8, 1],
         [5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3]],

        [[3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6]],

        [[8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4]]],


       [[[4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5]],

        [[0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3]],

        [[2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8]]]])

In [78]:
a4.shape, a4.ndim # dimension

((2, 3, 4, 5), 4)

In [79]:
# get the first 4 numbers of the inner most array 
a4[1:,2:,:1,:]

array([[[[2, 3, 4, 1, 2]]]])

### 4. Manipulating & comparing arrays 

In [80]:
a1

array([1, 2, 3])

In [84]:
ones = np.ones(3) 
ones

array([1., 1., 1.])

In [85]:
a1 + ones

array([2., 3., 4.])

In [86]:
a1 - ones

array([0., 1., 2.])

In [87]:
a1 * ones

array([1., 2., 3.])

In [88]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [89]:
a1 * a2

array([[ 1. ,  4. ,  9. ],
       [ 4. , 10. , 19.5]])

In [92]:
a3, a3.shape

(array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]), (2, 3, 3))

In [93]:
# a2 * a3
# how can we reshape a2 to be compatible with a3? 

numpy broadcasting: 

1. The term `broadcasting` describes how numpy treats arrays with different shapes during arithmetic operations.

2. When operating on two arrays, Numpy compares their shapes elements-wise. It starts with the trailing dimensions, and works its way forward. Twp diemsions are compatible when

1> they are equal, or

2> one of them is 1

In [94]:
a1 / ones

array([1., 2., 3.])

In [95]:
a2 / a1

array([[1.        , 1.        , 1.        ],
       [4.        , 2.5       , 2.16666667]])

In [96]:
# Floor divison remobes the decimals (rounds down)
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [99]:
print(a2 ** 2)
print(np.square(a2))

[[ 1.    4.    9.  ]
 [16.   25.   42.25]]
[[ 1.    4.    9.  ]
 [16.   25.   42.25]]


In [101]:
np.add(a1, ones), 
a1 + ones

array([2., 3., 4.])

In [ ]:
# numpy.mod
# Return element-wise remainder of division. 

In [102]:
a1 % 2

array([1, 0, 1], dtype=int32)

In [103]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [104]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

### Aggregation 

Aggregation = performing the same operation on a number of things 

In [105]:
listy_list = [1,2,3]
type(listy_list)

list

In [106]:
sum(listy_list)

6

In [107]:
a1

array([1, 2, 3])

In [108]:
type(a1)

numpy.ndarray

In [109]:
sum(a1)

6

In [110]:
np.sum(a1)

6

use Python's methods on Python datatypes(`sum()`) and 
use NumPy's methods on NumPy arrays(`np.sum()`)

In [113]:
# Creative a massive NumPy array
massive_array = np.random.random(100000)
massive_array.size

100000

In [114]:
massive_array[:100]

array([0.22204305, 0.92063245, 0.75837437, 0.58956424, 0.38768665,
       0.63767413, 0.72639352, 0.18929253, 0.40308868, 0.00768898,
       0.15904701, 0.1179556 , 0.30634003, 0.54127128, 0.13618746,
       0.44296673, 0.49657855, 0.65319272, 0.40871994, 0.72394184,
       0.01398129, 0.63201089, 0.88895725, 0.39731637, 0.94630207,
       0.17670341, 0.85611131, 0.48923787, 0.61994572, 0.92047766,
       0.99394347, 0.69426067, 0.35340783, 0.6127104 , 0.10053371,
       0.79920942, 0.21641944, 0.36264976, 0.09160374, 0.69929618,
       0.47549623, 0.5617212 , 0.14799486, 0.94197754, 0.64511419,
       0.04672772, 0.77031946, 0.07268371, 0.33184669, 0.51195386,
       0.33558122, 0.61901005, 0.67585614, 0.81628491, 0.02698436,
       0.6486616 , 0.43216547, 0.44731444, 0.76937984, 0.81825457,
       0.2354117 , 0.77496031, 0.69502174, 0.55224335, 0.37676736,
       0.93287148, 0.47076427, 0.28460015, 0.10464514, 0.36137371,
       0.7134388 , 0.07242945, 0.75993077, 0.24665936, 0.72670

In [115]:
%timeit sum(massive_array) # Python's sum()
%timeit np.sum(massive_array) # NumPy's np.sum()

# how long it takes particular lines to run 
# 7.26 ms ± 222 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
# 42.9 µs ± 5.33 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)

7.26 ms ± 222 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
42.9 µs ± 5.33 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [119]:
np.mean(a2), np.max(a2), np.std(a2), np.var(a2)
# Variance = measure of the average defree to which each number is different to the mean 
# High variance = wider range of numbers 
# Low variance = lower range of numbers 

(3.5833333333333335, 6.5, 1.8352262954621035, 3.368055555555556)

In [120]:
np.sqrt(np.var(a2))
# Standard deviation = sqareroot of variance 

1.8352262954621035